#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Delete older releases and workflows runs (Scheduled + Fixed Configuration)
#==========================================================================

name: Delete older releases

on:
  schedule:
    - cron: '59 23 * * 5'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      delete_releases:
        description: "Delete Releases file?"
        required: true
        default: true
        type: boolean
      delete_tags:
        description: "Delete related Tags?"
        required: true
        default: true
        type: boolean
      prerelease_option:
        description: "Whether to differentiate pre-release."
        required: true
        default: "all"
        type: choice
        options:
          - all
          - true
          - false
      delete_workflows:
        description: "Delete workflows records?"
        required: true
        default: true
        type: boolean
      out_log:
        description: "Output detailed JSON logs."
        required: false
        default: true
        type: boolean

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: >-
      github.event_name == 'schedule' || 
      github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: ${{ inputs.delete_releases }}
          delete_tags: ${{ inputs.delete_tags }}
          prerelease_option: ${{ inputs.prerelease_option }}
          releases_keep_latest: 3
          delete_workflows: ${{ inputs.delete_workflows }}
          workflows_keep_day: 1
          out_log: ${{ inputs.out_log }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
